name: Test macOS 14 Version

on:
  workflow_dispatch:  # This allows manual trigger from GitHub UI

jobs:
  check-macos-version:
    name: Check macOS 14 Version
    runs-on: macos-14  # This ensures it runs on macOS 14 version
    steps:
      - name: Check macOS Version
        run: sw_vers
