name: Check macOS Version (Strictly macOS 14)

on:
  workflow_dispatch:

jobs:
  check-version:
    name: Check macOS 14 Version
    runs-on: macos-latest-large
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display macOS version
        run: |
          echo "macOS Version: $(sw_vers -productVersion)"
        
      - name: Check architecture
        run: |
          ARCHITECTURE=$(uname -m)
          echo "Architecture is: $ARCHITECTURE"
          if [[ "$ARCHITECTURE" == "arm64" ]]; then
            echo "This is macOS 14 ARM architecture, exiting...";
            exit 1;
          fi
