name: Check macOS 14 Version

on:
  workflow_dispatch:

jobs:
  check-version:
    name: Check macOS 14 Version
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display macOS version
        run: |
          echo "macOS Version: $(sw_vers -productVersion)"
          
      - name: Verify architecture
        run: |
          uname -m  # To verify the architecture, should show either x86_64 or arm64
